- name: Create database 
  mysql_db:
    name: laravel_blog
    state: present
    
- name: create user
  mysql_user:
    name: laravel_user
    password: blog@101
    host: 172.16.20.112
    priv: 'laravel_blog.*:ALL'
    state: present

- name: firewall rule to allow app server to connect to db server
  community.general.ufw:
    rule: allow
    port: 3306
    proto: tcp
    from_ip: 172.16.20.112
  
- name: restart mysql service
  service:
    name: mysql
    state: restarted
