---
- name: Gathering facts
  package_facts:
    manager: auto

- name: Installing nginx
  apt:
    name: 
      - nginx
      - docker.io
      - docker-compose 
    state: present
  when: "'nginx' not in ansible_facts.packages and 'docker.io' not in ansible_facts.packages and 'docker-compose' not in ansible_facts.packages"

- name : Enable nginx
  service:
    name: nginx
    state: started
    enabled: true